### ISSUE TITLE
Current version is not compatible with nette/application 3.1.9

### ISSUE THREAD

**Issue by jkavalik** [contributte/tracy#27]
Hello, we just hit a problem on deploy, Nette App released a new version today and it replaces `$bar->addPanel(new Latte\Bridges\Tracy\LattePanel(..))` with `$template->getLatte()->addExtension(new Latte\Bridges\Tracy\TracyExtension($name));`
which throws an exception with contributte/tracy - [src/Bridges/ApplicationDI/LatteExtension.php](https://github.com/nette/application/commit/7b53e9d904888fadb35d92af762ba560af3d2ca6#diff-eeab2ced1aed0aa6bb1acf74b69ec04dd6c7b23fc7839473eaf8a768694d2640)

I expect more people to hit it soon. The simplest fix would be to do a new patch release with "conflicts", at least until the code is updated.

**Comment by namo-R** [comment]
Same problem here :)

**Comment by f3l1x** [comment]
Hi ✋ Problem is here https://github.com/contributte/tracy/blob/master/src/DI/NavigationPanelExtension.php?

**Comment by jkavalik** [comment]
@f3l1x Hm, it seems that I was too hasty and the actual problem is elsewhere, I am sorry.

@namo-R - https://github.com/nette/application/issues/311
